language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --colors -c phpunit.xml --coverage-clover=unittest-coverage.clover
  - ./vendor/bin/phpcs --standard=psr2 ./src