language: php

php:
  - 5.6
  - 7.0

install:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --colors -c phpunit.xml --coverage-clover=unittest-coverage.clover
  - ./vendor/bin/phpcs --standard=psr2 ./src
